### ISSUE TITLE
Dokumentation of Windows Installation

### ISSUE THREAD

**Issue by Narratot** [sandialabs/sceptre-phenix#165]
Hello,
I am trying to set up a Windows Image for the deployment within the Plattform. My problem is, that I did not find a documentation on which configuration steps are necessary to enable Windows to run within the Environment.
Can you provide me some help?
Thank you.

**Comment by Narratot** [comment]
I recommend to include the Minimega installation (<https://www.sandia.gov/minimega/module-28-miniccc-and-the-cc-api/>) for which I needed to download minimega and build it to optain the miniccc.exe
I used the following post installation steps:
1. Install Virtio Drivers (using current *.iso and the provided installer)
2. Install minimega executable following the steps in (<https://www.sandia.gov/minimega/module-28-miniccc-and-the-cc-api/>)

**Comment by activeshadow** [comment]
I'm closing this issue, as it's specific to minimega and not phēnix. Please feel free to re-open this issue in the minimega repo at https://github.com/sandia-minimega/minimega.
